### ISSUE TITLE
MIDI export

### ISSUE THREAD

**Issue by SambaGodschynski** [werckme/werckmeister-component#3]
as musican I' am able to export my sheets as MIDI file

**Comment by dirkk0** [comment]
I just discovered Werckmeister and I am thrilled, great work! Does the closing of this issue mean that the webcomponent is able to export MIDI? If yes, how?

**Comment by SambaGodschynski** [comment]
love to hear that you enoy Werckmeister.
the `werckmeister-snipped` component does not support the export.


but the `werckmeister-workspace` component does. It is the component which I use to implement the online editor on https://www.werckme.org

it allows you to register several editors in one "project".

here is an example:
https://jsfiddle.net/pmwnbc85/
